spring:
  application:
    name: resident-service
  
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  
  instance: 
     hostname: locahost